### ISSUE TITLE
compatibility with alien biome ?

### ISSUE THREAD

**Issue by Fr-Dae** [nicholasgower/planet-muluna#1]

**Comment by nicholasgower** [comment]
This mod uses Alien Biomes Graphics as a dependency to source Muluna's textures. I have not tested the mod with Alien Biomes yet. Once the backbone of the planet is in a more complete state, I'll look into resolving compatibility issues with other major mods. For now, it is best to use this mod with no other mods installed.

**Comment by nicholasgower** [comment]
If you have a crash report that indicates that Alien Biomes is incompatible with Muluna, I would appreciate it.

**Comment by Fr-Dae** [comment]
sure i will testing it later, have a nice day

**Comment by nicholasgower** [comment]
#4 Issue has been fixed in 1.4.1.
