### ISSUE TITLE
Oxidized boiler texture

### ISSUE THREAD

**Issue by Frontrider** [nicholasgower/planet-muluna#10]
**Is your feature request related to a problem? Please describe.**
Not a problem, only an asset.

**Describe the solution you'd like**
Use hurricane's thermal plant for the boiler?
https://www.figma.com/proto/y1IQG08ZG2jIeJ5sTyF4MP/Factorio-Buildings?node-id=14934-304&node-type=frame&t=tk88gXWNIga60zMr-0&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=2585%3A1158&hotspot-hints=0&hide-ui=1

High quality, and I think it fits into that slot. Can also allow you to change up the piping so it does not have to look the same as the one we have on Nauvis.

**Comment by nicholasgower** [comment]
I have not added this texture to the game yet, but I have added these assets to the mod's dependencies list. Thank you for informing me of these resources.
