### ISSUE TITLE
Regression: 1.9.10 broke Factorissimo 3 compatibility

### ISSUE THREAD

**Issue by Mashaaaaaaaaaaa** [nicholasgower/planet-muluna#21]
**Factorio & Muluna version number**
Muluna 1.9.10, Factorissimo 3 by notnotmelon version 3.7.10.

**Describe the bug**
Enabling both mods causes this bug:
Failed to load mods: ...ctorissimo-2-notnotmelon__/prototypes/space-location.lua:128: attempt to perform arithmetic on field 'distance' (a nil value)
stack traceback:
	...ctorissimo-2-notnotmelon__/prototypes/space-location.lua:128: in main chunk
	[C]: in function 'require'
	__factorissimo-2-notnotmelon__/data-updates.lua:1: in main chunk

**To Reproduce**
Steps to reproduce the behavior from a new save:
1. Enable both mods using the stated versions.
2. The game will fail to properly launch and will ask you to disable Factorissimo 3.

**Expected behavior**
The game should launch.

**Screenshots**
I can't screenshot anything useful other than the stack trace I already posted.

**Additional context**
I tried downgrading Factorissimo and it didn't fix the issue - after a lot of testing I narrowed down the problem to Muluna 1.9.10 - the game works fine on 1.9.9. I have multiple other planet mods installed, none of the others conflict with Factorissimo.

**Save file & log**
The log doesn't provide anything useful beyond the above.

**Comment by nicholasgower** [comment]
I see the issue. As of 1.9.10, Muluna's distance and angle values are undefined until the data.updates step. This is to accomodate support for Tiered Solar Systems. Thank you for letting me know. I'll issue a fix.

**Comment by Mashaaaaaaaaaaa** [comment]
Wow, that was quick. Thanks!
