### ISSUE TITLE
Crash up on loading space age

### ISSUE THREAD

**Issue by Solarwuff** [nicholasgower/planet-muluna#4]
Failed to load mods: Error while running setup for space-location prototype "muluna" (planet): medium-rock (decorative) does not have an autoplace specification.

Mods to be disabled:
• planet-muluna (1.4.0)

PS Both Alien Biomes and Alien Biomes Graphics are loaded

**Comment by Solarwuff** [comment]
can confirm that it's a conflict between your mood and Alien Biomes

**Comment by nicholasgower** [comment]
Issue has been fixed in 1.4.1. This is a temporary fix until vanilla entities removed by Alien Biomes have a suitable replacement. For now, Muluna will lack rocks of any kind when Alien Biomes is installed.
