### ISSUE TITLE
Signal Transmitter

### ISSUE THREAD

**Issue by VincentYankowsky** [nicholasgower/planet-muluna#8]
It says in order to continue with the research, it requires a signal transmitter into orbit.  I did just that and nothing happened with completion of the research.  Is this a bug?

**Comment by nicholasgower** [comment]
This looks like an engine bug. I will reach out to Wube to see if they can fix it. If they don't fix it soon, I'll replace that trigger with something else.

**Comment by nicholasgower** [comment]
If you want to skip this technology for now, open the editor and research the technology for free.

**Comment by nicholasgower** [comment]
Workaround has been added in version 1.6.6.

**Comment by VincentYankowsky** [comment]
Personally the technology is useful.  I have used this plenty on Space Exploration when delivery chests are full so that it does not cause damage.
